# Splunk Universal Forwarder - Windows Event Log Inputs
#
# Arquivo utilizado no endpoint Windows10 para coletar eventos do
# Sysmon, Security e System e encaminhá-los ao Splunk Enterprise.
#
# Caminho utilizado no laboratório:
# C:\Program Files\SplunkUniversalForwarder\etc\system\local\inputs.conf

[WinEventLog://Microsoft-Windows-Sysmon/Operational]
disabled = 0
start_from = oldest
current_only = 0
checkpointInterval = 5
index = main

[WinEventLog://Security]
disabled = 0
start_from = oldest
current_only = 0
checkpointInterval = 5
index = main

[WinEventLog://System]
disabled = 0
start_from = oldest
current_only = 0
checkpointInterval = 5
index = main
